name: First Workflow

on: [push]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v6

        - name: Multiple Commands
          run: |
            echo "Fist GitHub Action Job"
            ls -ltra
            cat README.md

        - name: ASCII
          run: cosway -f dog "WOF WOF" >> dog.txt
            
      #  - name: List files
      #   run: ls
      #
      # - name: Read file
      #   run: cat README.md